/* libportal-gtk4.vapi generated by vapigen, do not modify. */

[CCode (cprefix = "Xdp", gir_namespace = "XdpGtk4", gir_version = "1.0", lower_case_cprefix = "xdp_")]
namespace Xdp {
	[CCode (cheader_filename = "libportal-gtk4/portal-gtk4.h")]
	public static Xdp.Parent parent_new_gtk (Gtk.Window window);
}
